apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubemq-micronaut-k8s-sub
  namespace: kubemq
  labels:
    app: kubemq-micronaut-k8s-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubemq-micronaut-k8s-sub
  template:
    metadata:
      labels:
        app: kubemq-micronaut-k8s-sub
    spec:
      containers:
        - name: kubemq-micronaut-k8s-sub
          image: ricardodev2/kubemq-micronaut-k8s-sub:1.0.0
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: kubemq-micronaut-k8s-sub
  namespace: kubemq
  labels:
    app: kubemq-micronaut-k8s-sub
spec:
  ports:
    - port: 8081
      protocol: TCP
  selector:
    app: kubemq-micronaut-k8s-sub
  type: NodePort